// Mock car data
export const initialCars = [
  {
    id: "range-rover",
    brand: "لاند روفر",
    model: "رينج روفر فوج اس اي",
    price: "6,200,000",
    installment: "124,444",
    year: "2020",
    mileage: "45,000 كم",
    trim: "Highline",
    location: "الاسكندرية",
    isFeatured: true,
    isCertified: true,
    discountText: "خصم 40 ألف ج.م",
    image: "/assets/car_placeholder.png",
  },
  {
    id: "mercedes-c200",
    brand: "مرسيدس بنز",
    model: "C200 AMG Line",
    price: "3,850,000",
    installment: "78,500",
    year: "2022",
    mileage: "28,000 كم",
    trim: "AMG",
    location: "القاهرة",
    isFeatured: true,
    isCertified: true,
    image: "/assets/car_placeholder.png",
  },
  {
    id: "toyota-corolla",
    brand: "تويوتا",
    model: "كورولا هايلاند",
    price: "1,250,000",
    installment: "24,000",
    year: "2021",
    mileage: "62,000 كم",
    trim: "Luxury",
    location: "الجيزة",
    isFeatured: false,
    isCertified: true,
    discountText: "خصم 15 ألف ج.م",
    image: "/assets/car_placeholder.png",
  },
  {
    id: "bmw-320i",
    brand: "بي إم دبليو",
    model: "320i M Sport",
    price: "3,100,000",
    installment: "62,000",
    year: "2020",
    mileage: "54,000 كم",
    trim: "M Sport",
    location: "القاهرة",
    isFeatured: true,
    isCertified: true,
    image: "/assets/car_placeholder.png",
  },
  {
    id: "hyundai-tucson",
    brand: "هيونداي",
    model: "توسان Smart Plus",
    price: "1,750,000",
    installment: "35,000",
    year: "2022",
    mileage: "38,000 كم",
    trim: "Smart",
    location: "الاسكندرية",
    isFeatured: false,
    isCertified: true,
    image: "/assets/car_placeholder.png",
  },
  {
    id: "kia-sportage",
    brand: "كيا",
    model: "سبورتاج Topline",
    price: "1,980,000",
    installment: "39,000",
    year: "2021",
    mileage: "49,000 كم",
    trim: "Topline",
    location: "المنصورة",
    isFeatured: false,
    isCertified: true,
    discountText: "خصم 10 آلاف ج.م",
    image: "/assets/car_placeholder.png",
  },
  {
    id: "chery-tiggo",
    brand: "شيري",
    model: "تيجو 8 برو",
    price: "1,450,000",
    installment: "28,500",
    year: "2023",
    mileage: "15,000 كم",
    trim: "Flagship",
    location: "القاهرة",
    isFeatured: true,
    isCertified: true,
    image: "/assets/car_placeholder.png",
  },
  {
    id: "mini-cooper",
    brand: "ميني كوبر",
    model: "S Countryman",
    price: "2,400,000",
    installment: "48,000",
    year: "2019",
    mileage: "71,000 كم",
    trim: "S",
    location: "الجيزة",
    isFeatured: false,
    isCertified: true,
    image: "/assets/car_placeholder.png",
  },
  {
    id: "bmw-x5",
    brand: "بي إم دبليو",
    model: "X5",
    price: "620,000",
    installment: "12,444",
    year: "2023",
    mileage: "45,000 كم",
    trim: "Highline",
    location: "الاسكندرية",
    isFeatured: true,
    isCertified: true,
    discountText: "خصم 40 ألف ج.م",
    image: "/assets/why_cars.png",
  },
];
