export const reviews = [
  {
    name: "سارة أحمد",
    carInfo: "هونداي سنتافي GL 2018 دبل 2018 / مستعملة",
    comment: "امانة وسرعة وأفضل سعر في السوق!",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_1a.svg",
      "/assets/review_avatar_1b.svg",
      "/assets/review_avatar_1c.svg",
      "/assets/review_avatar_1d.svg",
      "/assets/review_avatar_1e.svg",
      "/assets/review_avatar_1f.svg",
      "/assets/review_avatar_1g.svg",
      "/assets/review_avatar_1h.svg",
      "/assets/review_avatar_1i.svg",
      "/assets/review_avatar_1j.svg",
    ],
  },
  {
    name: "فاطمة عبدالله",
    carInfo: "رينو تاليمان 2026 / جديدة",
    comment: "الجراج بيضمنلك العربية الصح ويخلصك من الهم. نصيحة مني جربوه!",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_1a.svg",
      "/assets/review_avatar_1b.svg",
      "/assets/review_avatar_1c.svg",
      "/assets/review_avatar_1d.svg",
      "/assets/review_avatar_1e.svg",
      "/assets/review_avatar_1f.svg",
      "/assets/review_avatar_1g.svg",
      "/assets/review_avatar_1h.svg",
      "/assets/review_avatar_1i.svg",
      "/assets/review_avatar_1j.svg",
    ],
  },
  {
    name: "أحمد محمود",
    carInfo: "تويوتا كامري 2023 / مستعملة",
    comment:
      "ضامن فحص كامل وتقييمات حقيقية من الناس. أحسن مكان لبيع عربيتك من غير اي غش",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_3a.svg",
      "/assets/review_avatar_3b.svg",
      "/assets/review_avatar_3c.svg",
      "/assets/review_avatar_3d.svg",
      "/assets/review_avatar_3e.svg",
      "/assets/review_avatar_3f.svg",
      "/assets/review_avatar_3g.svg",
      "/assets/review_avatar_3h.svg",
      "/assets/review_avatar_3i.svg",
    ],
  },
  {
    name: "أحمد محمود",
    carInfo: "تويوتا كامري 2023 / مستعملة",
    comment:
      "ضامن فحص كامل وتقييمات حقيقية من الناس. أحسن مكان لبيع عربيتك من غير اي غش",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_3a.svg",
      "/assets/review_avatar_3b.svg",
      "/assets/review_avatar_3c.svg",
      "/assets/review_avatar_3d.svg",
      "/assets/review_avatar_3e.svg",
      "/assets/review_avatar_3f.svg",
      "/assets/review_avatar_3g.svg",
      "/assets/review_avatar_3h.svg",
      "/assets/review_avatar_3i.svg",
    ],
  },
  {
    name: "أحمد محمود",
    carInfo: "تويوتا كامري 2023 / مستعملة",
    comment:
      "ضامن فحص كامل وتقييمات حقيقية من الناس. أحسن مكان لبيع عربيتك من غير اي غش",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_3a.svg",
      "/assets/review_avatar_3b.svg",
      "/assets/review_avatar_3c.svg",
      "/assets/review_avatar_3d.svg",
      "/assets/review_avatar_3e.svg",
      "/assets/review_avatar_3f.svg",
      "/assets/review_avatar_3g.svg",
      "/assets/review_avatar_3h.svg",
      "/assets/review_avatar_3i.svg",
    ],
  },
  {
    name: "أحمد محمود",
    carInfo: "تويوتا كامري 2023 / مستعملة",
    comment:
      "ضامن فحص كامل وتقييمات حقيقية من الناس. أحسن مكان لبيع عربيتك من غير اي غش",
    bgImage: "/assets/review_car_placeholder.png",
    avatars: [
      "/assets/review_avatar_3a.svg",
      "/assets/review_avatar_3b.svg",
      "/assets/review_avatar_3c.svg",
      "/assets/review_avatar_3d.svg",
      "/assets/review_avatar_3e.svg",
      "/assets/review_avatar_3f.svg",
      "/assets/review_avatar_3g.svg",
      "/assets/review_avatar_3h.svg",
      "/assets/review_avatar_3i.svg",
    ],
  },
];
